services:
  - type: web
    name: cashi-cloud-manager
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
